// Builds the in-page agent: src/index.ts -> dist/agent.iife.js (browser IIFE), then wraps it
// as an importable string constant in dist/index.js (see index.d.ts).
import { build } from "esbuild";
import { mkdir, readFile, writeFile } from "node:fs/promises";

await build({
  entryPoints: ["src/index.ts"],
  bundle: true,
  format: "iife",
  platform: "browser",
  target: "es2020",
  outfile: "dist/agent.iife.js",
  sourcemap: false,
  minify: false,
  logLevel: "warning",
});

const code = await readFile("dist/agent.iife.js", "utf8");
await mkdir("dist", { recursive: true });
await writeFile(
  "dist/index.js",
  `// generated by build.mjs — do not edit
const AGENT_CONFIG_SYMBOL = "@mirror/agent/config";
const AGENT_CODE = ${JSON.stringify(code)};
export const DEFAULT_AGENT_CONFIG = Object.freeze({
  canvas: Object.freeze({ fps: 8, quality: 0.7 }),
  bridge: Object.freeze({
    bindingName: "__mirror_emit",
    rtcBindingName: "__mirror_rtc_emit",
    bridgeKey: "__mirror_bridge",
    outboundEventName: "__mirror_outbound",
    inboundEventName: "__mirror_inbound",
    nodeResponseEventName: "__mirror_node_response",
    readyEventName: "__mirror_ready",
  }),
});
export function createAgentBundle(config = DEFAULT_AGENT_CONFIG) {
  const canvas = config && typeof config === "object" && config.canvas && typeof config.canvas === "object"
    ? config.canvas
    : {};
  const bridge = config && typeof config === "object" && config.bridge && typeof config.bridge === "object"
    ? config.bridge
    : {};
  const embedded = {
    canvas: { fps: canvas.fps, quality: canvas.quality },
    bridge: {
      bindingName: bridge.bindingName,
      rtcBindingName: bridge.rtcBindingName,
      bridgeKey: bridge.bridgeKey,
      outboundEventName: bridge.outboundEventName,
      inboundEventName: bridge.inboundEventName,
      nodeResponseEventName: bridge.nodeResponseEventName,
      readyEventName: bridge.readyEventName,
    },
  };
  return \`globalThis[Symbol.for(\${JSON.stringify(AGENT_CONFIG_SYMBOL)})]=\${JSON.stringify(embedded)};\\n\${AGENT_CODE}\`;
}
export const AGENT_BUNDLE = createAgentBundle();
`,
);
console.log(`@mirror/agent: bundled ${(code.length / 1024).toFixed(1)}KB agent`);
